### ISSUE TITLE
Running on CloudPebble

### ISSUE THREAD

**Issue by moshih** [C-D-Lewis/accelstream-pebble#1]
Hi! I'm beginning pebble dev and I imported this project into cloud pebble and when I tried to run it I got the following error. I'm not sure whats wrong.

Setting top to                           : /tmp/tmpqj3OGG 
Setting out to                           : /tmp/tmpqj3OGG/build 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK in			 : /app/sdk2/Pebble
'configure' finished successfully (0.054s)
Waf: Entering directory `/tmp/tmpqj3OGG/build'
[ 1/14] appinfo.auto.c: appinfo.json -> build/appinfo.auto.c
Waf: Leaving directory `/tmp/tmpqj3OGG/build'
Build failed
Traceback (most recent call last):
  File "/app/sdk2/Pebble/.waf-1.7.11-04343383b3a9511074383c51ae32d355/waflib/Task.py", line 123, in process
    ret=self.run()
  File "/app/sdk2/Pebble/.waf-1.7.11-04343383b3a9511074383c51ae32d355/waflib/Task.py", line 47, in run
    return m1(self)
  File "/app/sdk2/Pebble/.waf-1.7.11-04343383b3a9511074383c51ae32d355/waflib/extras/pebble_sdk.py", line 58, in _generate_appinfo_c_file_rule
    generate_appinfo.generate_appinfo(task.inputs[0].abspath(),task.outputs[0].abspath())
  File "/app/sdk2/Pebble/.waf-1.7.11-04343383b3a9511074383c51ae32d355/waflib/extras/generate_appinfo.py", line 42, in generate_appinfo
    raise Exception('appinfo.json versionLabel format for app revision must be "Major" or "Major.Minor"')
Exception: appinfo.json versionLabel format for app revision must be "Major" or "Major.Minor"

[ERROR   ] A compilation error occurred

**Comment by C-D-Lewis** [comment]
This is because this code is super old and needs to be updated, which I will do now.

**Comment by moshih** [comment]
Thank you sooooo much!!!! I'm actually doing research based on pebble accelerometer data.

**Comment by C-D-Lewis** [comment]
No problem. This should now be fixed, although the code style still leaves something to be desired. Good luck with your research!
